// Autogenerated from Pigeon (v0.1.0-experimental.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

@class PGNStringMessage;
@class PGNVoidMessage;

@interface PGNStringMessage : NSObject 
@property(nonatomic, copy) NSString * message;
@end

@interface PGNVoidMessage : NSObject 
@end

@protocol PGNApi
-(PGNStringMessage *)getPlatformVersion:(PGNVoidMessage*)input error:(FlutterError **)error;
@end

extern void PGNApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<PGNApi> api);

